# Generated by Django 5.1.5 on 2025-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='read', max_length=50),
        ),
    ]
