# Generated by Django 5.0.3 on 2025-06-23 12:50

import OWM.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0002_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, storage=OWM.utils.VideoMediaCloudinaryStorage(), upload_to='', verbose_name='gallery_videos'),
        ),
    ]
