# Generated by Django 5.0.3 on 2025-07-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0002_booking_invoice_number_teammember_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('photo-video', 'Photo & Video Shooting'), ('audio', 'Music Production'), ('graphic', 'Graphic Designing'), ('broadcasting', 'Digital Broadcasting')], max_length=20),
        ),
    ]
