# Generated by Django 5.0.3 on 2025-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0004_remove_customuser_address_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
