# Generated by Django 5.0.3 on 2025-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0004_alter_booking_status_alter_video_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=10),
        ),
    ]
