# Generated by Django 5.0.3 on 2025-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0005_teammember_tiktok_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='audio_category',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('photo-video', 'Photo & Video Shooting'), ('graphic', 'Graphic Designing'), ('broadcasting', 'Digital Broadcasting'), ('beat_making', 'Beat Making'), ('sound_recording', 'Sound Recording'), ('mixing', 'Mixing'), ('mastering', 'Mastering'), ('music_video', 'Music Video Production')], max_length=20),
        ),
    ]
