# Generated by Django 5.0.3 on 2025-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWM', '0006_remove_service_audio_category_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('photo-video', 'Photo & Video Shooting'), ('graphic', 'Graphic Designing'), ('broadcasting', 'Digital Broadcasting'), ('beat_making', 'Beat Making'), ('sound_recording', 'Sound Recording'), ('audio_mixing', 'Audio Mixing'), ('audio_mastering', 'Audio Mastering'), ('music_video', 'Music Video Production')], max_length=20),
        ),
    ]
